#!/usr/bin/env python3
"""Train the graph-blind soft-prompt baseline on the REAL CLEGR dataset
generated by scripts/generate_clegr_real.py, then evaluate on its held-out
test split -- the missing third leg of scripts/train_clegr_real.py's
TEA/GraphToken comparison (see documents/experiments/results/
v2_clegr_extended-20260919/report.md section 10).

Unlike train_clegr_real.py, there is no GNN phase at all: SoftPromptGLM
(src/graph_modi/models/soft_prompt.py) sees only the question text, never
the graph, via one learned prefix-token matrix shared across every example.
This directly tests, on our own real-CLEGR data/training pipeline (not
just by citing the source CLEGR paper's own claim, see report.md section
12), whether the graph-blind-matches-GLM finding this project already
reproduced in the dynamic synthetic-benchmark setting also holds on real
CLEGR.

Usage:
  CUDA_VISIBLE_DEVICES=<mig-uuid> HF_HOME=... \
    .venv/bin/python scripts/train_soft_prompt_clegr_real.py \
    --gpu-memory-fraction 0.4 --data-dir datasets/clegr_real \
    --output-dir outputs/clegr_real_soft_prompt
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any


def _apply_gpu_memory_cap(fraction: float) -> None:
    import torch

    if fraction >= 1.0 or not torch.cuda.is_available():
        return
    torch.cuda.set_per_process_memory_fraction(fraction, device=0)
    print(f"[clegr-real-soft-prompt] capped this process to {fraction:.0%} of GPU memory", flush=True)


def _load_examples(path: Path) -> list[Any]:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from graph_modi.schema import AttributedGraph
    from graph_modi.training import TrainingExample

    examples = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            examples.append(
                TrainingExample(
                    graph=AttributedGraph.from_dict(record["graph"]),
                    prompt=record["prompt"],
                    answer=record["answer"],
                    example_id=record["example_id"],
                    split=record["split"],
                    metadata=record["metadata"],
                )
            )
    return examples


_BOOL_TRUE = {"true", "yes", "1"}
_BOOL_FALSE = {"false", "no", "0"}


def _normalize(text: str) -> str:
    return re.sub(r"[^\w\s,.-]", "", text.strip().lower())


def _score(gold: str, pred: str) -> bool:
    gold_norm, pred_norm = _normalize(gold), _normalize(pred)
    if gold_norm in _BOOL_TRUE or gold_norm in _BOOL_FALSE:
        pred_bool = pred_norm in _BOOL_TRUE
        gold_bool = gold_norm in _BOOL_TRUE
        return pred_bool == gold_bool and (pred_norm in _BOOL_TRUE or pred_norm in _BOOL_FALSE)
    try:
        return abs(float(gold_norm) - float(re.sub(r"[^\d.\-]", "", pred_norm))) < 1e-6
    except ValueError:
        pass
    if "," in gold:
        gold_set = {item.strip().lower() for item in gold.split(",") if item.strip()}
        pred_set = {item.strip().lower() for item in pred.split(",") if item.strip()}
        return gold_set == pred_set
    return gold_norm == pred_norm


def _evaluate(model, test_examples, batch_size: int, max_new_tokens: int) -> dict[str, Any]:
    rows = []
    for offset in range(0, len(test_examples), batch_size):
        batch = test_examples[offset : offset + batch_size]
        predictions = model.generate_batch(
            prompts=[example.prompt for example in batch],
            max_new_tokens=max_new_tokens,
        )
        for example, predicted in zip(batch, predictions, strict=True):
            correct = _score(example.answer, predicted)
            rows.append(
                {
                    "clegr_type": example.metadata.get("clegr_type"),
                    "clegr_group": example.metadata.get("clegr_group"),
                    "clegr_subgroup": example.metadata.get("clegr_subgroup"),
                    "gold": example.answer,
                    "predicted": predicted,
                    "correct": correct,
                }
            )
        if (offset // batch_size) % 20 == 0:
            done = min(offset + batch_size, len(test_examples))
            running_acc = sum(r["correct"] for r in rows) / len(rows)
            print(f"[clegr-real-soft-prompt] eval {done}/{len(test_examples)} running_acc={running_acc:.4f}", flush=True)

    def _bucket(key: str) -> dict[str, float]:
        groups: dict[str, list[bool]] = defaultdict(list)
        for row in rows:
            groups[str(row[key])].append(row["correct"])
        return {name: sum(vals) / len(vals) for name, vals in sorted(groups.items())}

    overall = sum(row["correct"] for row in rows) / len(rows)
    return {
        "overall_accuracy": overall,
        "n": len(rows),
        "by_type": _bucket("clegr_type"),
        "by_group": _bucket("clegr_group"),
        "by_subgroup": _bucket("clegr_subgroup"),
        "rows": rows,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default="datasets/clegr_real")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--gpu-memory-fraction", type=float, default=0.9)
    parser.add_argument("--gradient-checkpointing", action="store_true")
    parser.add_argument("--lm-name", default="/data/lmw/models/Meta-Llama-3.1-8B-Instruct")
    parser.add_argument("--prefix-tokens", type=int, default=10)
    parser.add_argument(
        "--max-sequence-length",
        type=int,
        default=512,
        help="raise for CSV-textualized-graph prompts (clegr.md 8.2), which run ~1400+ tokens",
    )
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=3)
    parser.add_argument("--learning-rate", type=float, default=5e-4)
    parser.add_argument("--max-new-tokens", type=int, default=32)
    parser.add_argument("--eval-batch-size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--skip-training", action="store_true", help="evaluate an existing checkpoint only")
    args = parser.parse_args()

    _apply_gpu_memory_cap(args.gpu_memory_fraction)

    import torch

    from graph_modi.models.soft_prompt import SoftPromptConfig, SoftPromptGLM, load_soft_prompt_checkpoint
    from graph_modi.training import ProjectorTrainingConfig, train_soft_prompt

    data_dir = Path(args.data_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("[clegr-real-soft-prompt] loading examples...", flush=True)
    train_examples = _load_examples(data_dir / "train.jsonl")
    test_examples = _load_examples(data_dir / "test.jsonl")
    print(f"[clegr-real-soft-prompt] train={len(train_examples)} test={len(test_examples)}", flush=True)

    checkpoint_dir = output_dir / "soft_prompt" / "checkpoint-final"

    if not args.skip_training:
        print("[clegr-real-soft-prompt] building model (frozen LLM + learned prefix, no GNN)", flush=True)
        model = SoftPromptGLM.from_pretrained(
            args.lm_name,
            prefix_tokens=args.prefix_tokens,
            torch_dtype=torch.bfloat16,
            config=SoftPromptConfig(prefix_tokens=args.prefix_tokens, max_sequence_length=args.max_sequence_length),
        )
        if args.gradient_checkpointing:
            model.language_model.gradient_checkpointing_enable()
            model.language_model.enable_input_require_grads()
            print("[clegr-real-soft-prompt] gradient checkpointing enabled on the frozen LLM", flush=True)

        train_config = ProjectorTrainingConfig(
            output_dir=output_dir / "soft_prompt",
            epochs=args.epochs,
            batch_size=args.batch_size,
            gradient_accumulation_steps=args.gradient_accumulation_steps,
            learning_rate=args.learning_rate,
            mixed_precision="bf16",
            save_every_steps=2000,
            seed=args.seed,
        )
        print("[clegr-real-soft-prompt] training soft prompt", flush=True)
        train_soft_prompt(model, train_examples, train_config)
    else:
        print("[clegr-real-soft-prompt] --skip-training: loading existing checkpoint for eval only", flush=True)
        model = SoftPromptGLM.from_pretrained(
            args.lm_name,
            prefix_tokens=args.prefix_tokens,
            torch_dtype=torch.bfloat16,
            config=SoftPromptConfig(prefix_tokens=args.prefix_tokens, max_sequence_length=args.max_sequence_length),
        )
        load_soft_prompt_checkpoint(model, checkpoint_dir=checkpoint_dir)

    print("[clegr-real-soft-prompt] evaluating on real CLEGR test split", flush=True)
    model.eval()

    with torch.no_grad():
        result = _evaluate(model, test_examples, args.eval_batch_size, args.max_new_tokens)

    print(f"\n=== soft_prompt on real CLEGR test ({result['n']} examples) ===")
    print("overall_accuracy:", round(result["overall_accuracy"], 4))
    print("by_group:", {k: round(v, 4) for k, v in result["by_group"].items()})
    print("by_subgroup:", {k: round(v, 4) for k, v in result["by_subgroup"].items()})
    for type_name, acc in sorted(result["by_type"].items(), key=lambda kv: -kv[1]):
        print(f"  {type_name}: {round(acc, 4)}")

    out_path = output_dir / "clegr_real_eval.json"
    out_path.write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")
    print(f"[clegr-real-soft-prompt] wrote {out_path}", flush=True)


if __name__ == "__main__":
    main()
