#!/usr/bin/env python3
"""Train TEA-GLM or GraphToken (this project's own pooled-readout
architecture, not the aspect/multi-neighbor exploratory readouts) on the
REAL CLEGR dataset generated by scripts/generate_clegr_real.py, then
evaluate on its held-out test split.

Two-phase, same shape as every other training run in this project:
  Phase 1 -- pretrain a fresh GNN from scratch on the CLEGR training split
             (reuses pretrain_graph_encoder, same function used everywhere
             else in this project). Shared between --method tea and
             --method graphtoken (GraphToken warm-starts from it, matching
             this project's existing convention for the synthetic
             benchmark, then continues training it jointly).
  Phase 2 -- tea: freeze that GNN, train only the projector
                  (train_projector).
             graphtoken: unfreeze the GNN, train GNN+projector jointly
                  (train_graph_token).
  Phase 3 -- evaluate on the CLEGR test split by calling
             TEAGLM.generate_batch(...) directly (bypassing
             TEAGLMBackend/ModelInput/GraphQuery, which require a
             ReasoningType this dataset doesn't have -- CLEGR examples
             carry no reasoning_type/hops/source_id/target_id metadata,
             matching what they were trained with). Scored per-example with
             a format-inferring scorer mirroring CLEGR's own evaluator
             logic (exact/boolean/numeric-isclose/list-set-F1 dispatch by
             answer shape, not a hardcoded type-string table), bucketed by
             the real `clegr_type`/`clegr_group`/`clegr_subgroup` labels
             carried in each example's metadata.

Usage:
  CUDA_VISIBLE_DEVICES=<mig-uuid> HF_HOME=... \
    .venv/bin/python scripts/train_clegr_real.py --method tea \
    --gpu-memory-fraction 0.9 --data-dir datasets/clegr_real \
    --output-dir outputs/clegr_real_tea --gnn-dir outputs/clegr_real/gnn
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any


def _apply_gpu_memory_cap(fraction: float) -> None:
    import torch

    if fraction >= 1.0 or not torch.cuda.is_available():
        return
    torch.cuda.set_per_process_memory_fraction(fraction, device=0)
    print(f"[clegr-real] capped this process to {fraction:.0%} of GPU memory", flush=True)


def _load_examples(path: Path) -> list[Any]:
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from graph_modi.schema import AttributedGraph
    from graph_modi.training import TrainingExample

    examples = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            examples.append(
                TrainingExample(
                    graph=AttributedGraph.from_dict(record["graph"]),
                    prompt=record["prompt"],
                    answer=record["answer"],
                    example_id=record["example_id"],
                    split=record["split"],
                    metadata=record["metadata"],
                )
            )
    return examples


def _build_fresh_gnn(node_feature_size: int, graph_hidden_size: int, graph_layers: int, graph_aggregation: str):
    """Returns (graph_config, gnn, tensor_config) -- tensor_config is the
    NodeTensorizerConfig, not a tensorizer instance (TEAGLM.from_pretrained
    wants the config and builds its own tensorizer from it; callers that
    need an actual tensorizer instance, e.g. pretrain_graph_encoder, should
    wrap it themselves: DeterministicNodeTensorizer(tensor_config))."""
    from graph_modi.models.tea_glm import GraphSAGEConfig, GraphSAGEEncoder, NodeTensorizerConfig

    tensor_config = NodeTensorizerConfig(feature_dim=node_feature_size)
    graph_config = GraphSAGEConfig(
        input_dim=tensor_config.feature_dim,
        hidden_dim=graph_hidden_size,
        output_dim=graph_hidden_size,
        num_layers=graph_layers,
        aggregation=graph_aggregation,
    )
    return graph_config, GraphSAGEEncoder(graph_config), tensor_config


def _run_gnn_pretrain(train_examples, gnn_dir: Path, args) -> None:
    from graph_modi.models.tea_glm import DeterministicNodeTensorizer
    from graph_modi.training import pretrain_graph_encoder

    if (gnn_dir / "gnn.pt").exists() and not args.force_gnn_pretrain:
        print(f"[clegr-real] GNN checkpoint already exists at {gnn_dir}, skipping pretrain", flush=True)
        return
    _, gnn, tensor_config = _build_fresh_gnn(
        args.node_feature_size, args.graph_hidden_size, args.graph_layers, args.graph_aggregation
    )
    tensorizer = DeterministicNodeTensorizer(tensor_config)
    print(f"[clegr-real] pretraining GNN from scratch: {len(train_examples)} examples, epochs={args.gnn_epochs}", flush=True)
    result = pretrain_graph_encoder(
        gnn,
        tensorizer,
        train_examples,
        output_dir=gnn_dir,
        epochs=args.gnn_epochs,
        batch_size=args.gnn_batch_size,
        learning_rate=args.gnn_learning_rate,
        seed=args.seed,
    )
    print(f"[clegr-real] GNN pretrain done: {result}", flush=True)


def _build_model(args, freeze_gnn: bool):
    import torch

    from graph_modi.models.tea_glm import TEAGLM, TEAGLMConfig

    graph_config, _, tensor_config = _build_fresh_gnn(
        args.node_feature_size, args.graph_hidden_size, args.graph_layers, args.graph_aggregation
    )
    model = TEAGLM.from_pretrained(
        args.lm_name,
        gnn_config=graph_config,
        tensorizer_config=tensor_config,
        config=TEAGLMConfig(freeze_gnn=freeze_gnn, max_sequence_length=args.max_sequence_length),
        torch_dtype=torch.bfloat16,
        prefix_tokens=args.prefix_tokens,
        projector_hidden_dim=args.projector_hidden_size,
        projector_num_layers=args.projector_num_layers,
    )
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    if args.gradient_checkpointing:
        # The LLM's own parameters are frozen -- nothing here trains except
        # the graph-prefix embeddings feeding into it -- but backprop still
        # has to flow THROUGH every frozen layer to reach them, which by
        # default means PyTorch retains that layer's activations for the
        # whole forward pass. Checkpointing recomputes them during backward
        # instead of storing them, trading compute for the activation memory
        # that has been the actual OOM cause in this shared-GPU control run
        # (repeatedly failing at ~22GB regardless of batch size, since batch
        # size wasn't the dominant term -- per-layer activation retention
        # across the full 8B-parameter, ~32-layer stack was).
        model.language_model.gradient_checkpointing_enable()
        model.language_model.enable_input_require_grads()
        print("[clegr-real] gradient checkpointing enabled on the frozen LLM", flush=True)
    return model


def _load_gnn_checkpoint(model, gnn_dir: Path) -> None:
    import torch

    model.gnn.load_state_dict(torch.load(gnn_dir / "gnn.pt", map_location="cpu", weights_only=True), strict=True)


# --- Evaluation: format-inferring scorer, mirroring CLEGR's own dispatch
# (exact / boolean / numeric-isclose / list-set) but keyed off the answer's
# own shape rather than a hardcoded per-type-string table, since this
# project doesn't vendor their QUESTION_METADATA scope/subgroup table.

_BOOL_TRUE = {"true", "yes", "1"}
_BOOL_FALSE = {"false", "no", "0"}


def _normalize(text: str) -> str:
    return re.sub(r"[^\w\s,.-]", "", text.strip().lower())


def _score(gold: str, pred: str) -> bool:
    gold_norm, pred_norm = _normalize(gold), _normalize(pred)
    if gold_norm in _BOOL_TRUE or gold_norm in _BOOL_FALSE:
        pred_bool = pred_norm in _BOOL_TRUE
        gold_bool = gold_norm in _BOOL_TRUE
        return pred_bool == gold_bool and (pred_norm in _BOOL_TRUE or pred_norm in _BOOL_FALSE)
    try:
        return abs(float(gold_norm) - float(re.sub(r"[^\d.\-]", "", pred_norm))) < 1e-6
    except ValueError:
        pass
    if "," in gold:
        gold_set = {item.strip().lower() for item in gold.split(",") if item.strip()}
        pred_set = {item.strip().lower() for item in pred.split(",") if item.strip()}
        return gold_set == pred_set
    return gold_norm == pred_norm


def _evaluate(model, test_examples, batch_size: int, max_new_tokens: int) -> dict[str, Any]:
    rows = []
    for offset in range(0, len(test_examples), batch_size):
        batch = test_examples[offset : offset + batch_size]
        predictions = model.generate_batch(
            graphs=[example.graph for example in batch],
            prompts=[example.prompt for example in batch],
            source_ids=[example.metadata.get("source_id") for example in batch],
            target_ids=[example.metadata.get("target_id") for example in batch],
            max_new_tokens=max_new_tokens,
        )
        for example, predicted in zip(batch, predictions, strict=True):
            correct = _score(example.answer, predicted)
            rows.append(
                {
                    "clegr_type": example.metadata.get("clegr_type"),
                    "clegr_group": example.metadata.get("clegr_group"),
                    "clegr_subgroup": example.metadata.get("clegr_subgroup"),
                    "gold": example.answer,
                    "predicted": predicted,
                    "correct": correct,
                }
            )
        if (offset // batch_size) % 20 == 0:
            done = min(offset + batch_size, len(test_examples))
            running_acc = sum(r["correct"] for r in rows) / len(rows)
            print(f"[clegr-real] eval {done}/{len(test_examples)} running_acc={running_acc:.4f}", flush=True)

    def _bucket(key: str) -> dict[str, float]:
        groups: dict[str, list[bool]] = defaultdict(list)
        for row in rows:
            groups[str(row[key])].append(row["correct"])
        return {name: sum(vals) / len(vals) for name, vals in sorted(groups.items())}

    overall = sum(row["correct"] for row in rows) / len(rows)
    return {
        "overall_accuracy": overall,
        "n": len(rows),
        "by_type": _bucket("clegr_type"),
        "by_group": _bucket("clegr_group"),
        "by_subgroup": _bucket("clegr_subgroup"),
        "rows": rows,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--method", choices=["tea", "graphtoken"], required=True)
    parser.add_argument("--data-dir", default="datasets/clegr_real")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--gnn-dir", default="outputs/clegr_real/gnn", help="shared GNN pretrain checkpoint dir")
    parser.add_argument("--gpu-memory-fraction", type=float, default=0.9)
    parser.add_argument("--force-gnn-pretrain", action="store_true")
    parser.add_argument("--gradient-checkpointing", action="store_true")
    parser.add_argument("--lm-name", default="/data/lmw/models/Meta-Llama-3.1-8B-Instruct")
    parser.add_argument("--node-feature-size", type=int, default=64)
    parser.add_argument("--graph-hidden-size", type=int, default=4096)
    parser.add_argument("--graph-layers", type=int, default=8)
    parser.add_argument("--graph-aggregation", default="sum")
    parser.add_argument("--prefix-tokens", type=int, default=10)
    parser.add_argument(
        "--max-sequence-length",
        type=int,
        default=512,
        help="raise for CSV-textualized-graph prompts (clegr.md 8.2), which run ~1400+ tokens",
    )
    parser.add_argument("--projector-hidden-size", type=int, default=512)
    parser.add_argument("--projector-num-layers", type=int, default=1)
    parser.add_argument("--gnn-epochs", type=int, default=30)
    parser.add_argument("--gnn-batch-size", type=int, default=64)
    parser.add_argument("--gnn-learning-rate", type=float, default=0.002)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--gradient-accumulation-steps", type=int, default=3)
    parser.add_argument("--learning-rate", type=float, default=5e-4)
    parser.add_argument("--max-new-tokens", type=int, default=32)
    parser.add_argument("--eval-batch-size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--skip-training", action="store_true", help="evaluate an existing checkpoint only")
    args = parser.parse_args()

    _apply_gpu_memory_cap(args.gpu_memory_fraction)

    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
    from graph_modi.training import ProjectorTrainingConfig, train_projector

    data_dir = Path(args.data_dir)
    gnn_dir = Path(args.gnn_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("[clegr-real] loading examples...", flush=True)
    train_examples = _load_examples(data_dir / "train.jsonl")
    test_examples = _load_examples(data_dir / "test.jsonl")
    print(f"[clegr-real] train={len(train_examples)} test={len(test_examples)}", flush=True)

    if not args.skip_training:
        print("[clegr-real] phase 1: GNN pretrain (shared)", flush=True)
        _run_gnn_pretrain(train_examples, gnn_dir, args)

        print(f"[clegr-real] phase 2: building model (method={args.method})", flush=True)
        freeze_gnn = args.method == "tea"
        model = _build_model(args, freeze_gnn=freeze_gnn)
        _load_gnn_checkpoint(model, gnn_dir)
        if freeze_gnn:
            model.set_gnn_frozen(True)

        train_config = ProjectorTrainingConfig(
            output_dir=output_dir / "projector",
            epochs=args.epochs,
            batch_size=args.batch_size,
            gradient_accumulation_steps=args.gradient_accumulation_steps,
            learning_rate=args.learning_rate,
            mixed_precision="bf16",
            save_every_steps=2000,
            seed=args.seed,
        )
        print(f"[clegr-real] phase 2: training ({args.method})", flush=True)
        if args.method == "tea":
            train_projector(model, train_examples, train_config)
        else:
            from graph_modi.models.graph_token import train_graph_token

            train_graph_token(model, train_examples, train_config)
    else:
        print("[clegr-real] --skip-training: loading existing checkpoint for eval only", flush=True)
        model = _build_model(args, freeze_gnn=(args.method == "tea"))
        from graph_modi.models.tea_glm import load_external_component

        checkpoint_dir = output_dir / "projector" / "checkpoint-final"
        metadata_path = checkpoint_dir / "metadata.json"
        load_external_component(model, component="gnn", weights_path=checkpoint_dir / "gnn.pt", metadata_path=metadata_path)
        load_external_component(model, component="projector", weights_path=checkpoint_dir / "projector.pt", metadata_path=metadata_path)

    print("[clegr-real] phase 3: evaluating on real CLEGR test split", flush=True)
    model.eval()
    import torch

    with torch.no_grad():
        result = _evaluate(model, test_examples, args.eval_batch_size, args.max_new_tokens)

    print(f"\n=== {args.method} on real CLEGR test ({result['n']} examples) ===")
    print("overall_accuracy:", round(result["overall_accuracy"], 4))
    print("by_group:", {k: round(v, 4) for k, v in result["by_group"].items()})
    print("by_subgroup:", {k: round(v, 4) for k, v in result["by_subgroup"].items()})
    for type_name, acc in sorted(result["by_type"].items(), key=lambda kv: -kv[1]):
        print(f"  {type_name}: {round(acc, 4)}")

    out_path = output_dir / "clegr_real_eval.json"
    out_path.write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")
    print(f"[clegr-real] wrote {out_path}", flush=True)


if __name__ == "__main__":
    main()
